package com.example.unitconverter.recyclerViewData

import android.content.Context
import com.example.unitconverter.R

class DataStorage(override val context: Context) : RecyclerDataAbstractClass() {
    //constants //
    private val _byte = getString(R.string._byte)
    private val byte = _byte.toLowerCase(locale)
    private val byteUnit = getString(R.string.byte_unit)
    private val _bit = getString(R.string.bit)
    private val bit = _bit.toLowerCase(locale)
    private val yobi = getString(R.string.yobi)
    private val yobiUnit = getString(R.string.yobi_unit)
    private val zebi = getString(R.string.zebi)
    private val zebiUnit = getString(R.string.zebi_unit)
    private val exbi = getString(R.string.exbi)
    private val exbiUnit = getString(R.string.exbi_unit)
    private val pebi = getString(R.string.pebi)
    private val pebiUnit = getString(R.string.pebi_unit)
    private val tebi = getString(R.string.tebi)
    private val tebiUnit = getString(R.string.tebi_unit)
    private val gibi = getString(R.string.gibi)
    private val gibiUnit = getString(R.string.gibi_unit)
    private val mebi = getString(R.string.mebi)
    private val mebiUnit = getString(R.string.mebi_unit)
    private val kibi = getString(R.string.kibi)
    private val kibiUnit = getString(R.string.kibi_unit)

    override fun getList() = buildRecyclerList(35) {
        add(_bit, bit)
        add(getString(R.string.nibble), getString(R.string.nibble_unit))
        add(_byte, byteUnit)
        add(yobi + bit, yobiUnit + bit)
        add(zebi + bit, zebiUnit + bit)
        add(exbi + bit, exbiUnit + bit)
        add(pebi + bit, pebiUnit + bit)
        add(tebi + bit, tebiUnit + bit)
        add(gibi + bit, gibiUnit + bit)
        add(mebi + bit, mebiUnit + bit)
        add(kibi + bit, kibiUnit + bit)
        add(yobi + byte, yobiUnit + byteUnit)
        add(zebi + byte, zebiUnit + byteUnit)
        add(exbi + byte, exbiUnit + byteUnit)
        add(pebi + byte, pebiUnit + byteUnit)
        add(tebi + byte, tebiUnit + byteUnit)
        add(gibi + byte, gibiUnit + byteUnit)
        add(mebi + byte, mebiUnit + byteUnit)
        add(kibi + byte, kibiUnit + byteUnit)
        add(yotta + byte, yottaSymbol + byteUnit)
        add(zetta + byte, zettaSymbol + byteUnit)
        add(exa + byte, exaSymbol + byteUnit)
        add(peta + byte, petaSymbol + byteUnit)
        add(tera + byte, teraSymbol + byteUnit)
        add(giga + byte, gigaSymbol + byteUnit)
        add(mega + byte, megaSymbol + byteUnit)
        add(kilo + byte, kiloSymbol + byteUnit)
        add(yotta + bit, yottaSymbol + bit)
        add(zetta + bit, zettaSymbol + bit)
        add(exa + bit, exaSymbol + bit)
        add(peta + bit, petaSymbol + bit)
        add(tera + bit, teraSymbol + bit)
        add(giga + bit, gigaSymbol + bit)
        add(mega + bit, megaSymbol + bit)
        add(kilo + bit, kiloSymbol + bit)
    }
}